services:

  web:
    build: .
    container_name: url_shortener_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: url_shortener_postgres
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: url_shortener_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: url_shortener_redis
    ports:
      - "6379:6379"      

  celery_worker:
    build: .
    command: celery -A config.celery:app worker -l info
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A config.celery:app beat -l info
    depends_on:
      - redis
    env_file:
      - .env

  k6:
    image: grafana/k6
    volumes:
      - .:/app
    profiles:
      - testing

volumes:
  postgres_data: