services:

  web:
    build:
      context: ./backend
    container_name: url_shortener_web
    command: python manage.py runserver 0.0.0.0:8000
    # command: >
    #   gunicorn config.wsgi:application
    #   --bind 0.0.0.0:8000
    #   --workers 4
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - keycloak
      - redis
      - rabbitmq
      - clickhouse
    env_file:
      - ./backend/.env

  postgres:
    image: postgres:16
    container_name: url_shortener_postgres
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: url_shortener_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: url_shortener_redis
    ports:
      - "6379:6379"      


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  click_events_consumer:
    build:
      context: ./backend
    command: python manage.py consume_click_events
    depends_on:
      - rabbitmq
      - redis 
      - postgres
    env_file:
      - ./backend/.env

  click_counters_consumer:
    build:
      context: ./backend
    command: python manage.py consume_click_counters
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
      - redis 
      - postgres
    env_file:
      - ./backend/.env


  click_flusher:
    build:
      context: ./backend
    command: >
      sh -c "
      while true; do
        python manage.py flush_clicks;
        sleep 60;
      done
      "
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - ./backend/.env
  
  k6:
    image: grafana/k6
    volumes:
      - ./backend:/app
    profiles:
      - testing

  
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: url_shortener_clickhouse

    ports:
      - "8123:8123"   # HTTP API
      - "9000:9000"   # Native protocol
    
    environment:
      CLICKHOUSE_DB: analytics

      CLICKHOUSE_USER: analytics
      CLICKHOUSE_PASSWORD: analytics_password

      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./backend/analytics/clickhouse/schema:/docker-entrypoint-initdb.d
    
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10



  postgres_keycloak:
    image: postgres:17
    container_name: keycloak_postgres

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password

    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data


  keycloak:

    image: keycloak/keycloak:latest

    container_name: keycloak

    command: start-dev

    depends_on:
      - postgres_keycloak

    environment:

      KC_DB: postgres

      KC_DB_URL_HOST: postgres_keycloak

      KC_DB_URL_DATABASE: keycloak

      KC_DB_USERNAME: keycloak

      KC_DB_PASSWORD: keycloak_password

      KC_BOOTSTRAP_ADMIN_USERNAME: admin

      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:

      - "8080:8080"

  next-spa:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: url_shortener_spa

    ports:
      - "3000:3000"

    depends_on:
      - web
      - keycloak

volumes:
  postgres_data:
  clickhouse_data:  
  keycloak_postgres_data:
