services:

  web:
    build: .
    container_name: url_shortener_web
    command: python manage.py runserver 0.0.0.0:8000
    # command: >
    #   gunicorn config.wsgi:application
    #   --bind 0.0.0.0:8000
    #   --workers 4
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: url_shortener_postgres
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: url_shortener_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: url_shortener_redis
    ports:
      - "6379:6379"      


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  click_events_consumer:
    build: .
    command: python manage.py consume_click_events
    depends_on:
      - rabbitmq
      - redis 
      - postgres
    env_file:
      - .env

  click_counters_consumer:
    build: .
    command: python manage.py consume_click_counters
    depends_on:
      - rabbitmq
      - redis 
      - postgres
    env_file:
      - .env


  click_flusher:
    build: .
    command: >
      sh -c "
      while true; do
        python manage.py flush_clicks;
        sleep 60;
      done
      "
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
  
  k6:
    image: grafana/k6
    volumes:
      - .:/app
    profiles:
      - testing

  
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: url_shortener_clickhouse

    ports:
      - "8123:8123"   # HTTP API
      - "9000:9000"   # Native protocol
    
    environment:
      CLICKHOUSE_DB: analytics

      CLICKHOUSE_USER: analytics
      CLICKHOUSE_PASSWORD: analytics_password

      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./analytics/clickhouse/schema:/docker-entrypoint-initdb.d
    
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  clickhouse_data:  