# Generated by Django 6.0.5 on 2026-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_clickevent_short_url_clickevent_short_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('owner_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
