# Generated by Django 6.0.5 on 2026-08-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkOwnership',
            fields=[
                ('short_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
