# Generated by Django 6.0.5 on 2026-06-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickevent',
            name='short_url',
        ),
        migrations.AddField(
            model_name='clickevent',
            name='short_code',
            field=models.CharField(db_index=True, default='gooz', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='referrer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='user_agent',
            field=models.TextField(null=True),
        ),
    ]
