# Generated by Django 6.0.5 on 2026-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkownership',
            name='original_url',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
