# Generated by Django 6.0.5 on 2026-07-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_linkownership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickEvent',
        ),
        migrations.RemoveField(
            model_name='linkownership',
            name='id',
        ),
        migrations.AlterField(
            model_name='linkownership',
            name='owner_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkownership',
            name='short_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
