# Generated by Django 6.0.5 on 2026-05-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
    ]
